name: Terraform AWS Deployment

on:
  push:
    branches:
      - RAMA

jobs:
  despliegue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: CONFIGURAR CREDENCIALES AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: "us-east-1"

      - name: INSTALAR TERRAFORM EN LA MÁQUINA VIRTUAL
        uses: 

      - name: INICIALIZAR TERRAFORM
        run: 
       

      - name: Plan Terraform
        run: 

      - name: Apply Terraform
        run: 
